// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:traeu/data/models/user_activity.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BrowseHistoryAdapter());
    registerAdapter(FrequentlyVisitedAdapter());
    registerAdapter(LocalFavoriteAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BrowseHistoryAdapter());
    registerAdapter(FrequentlyVisitedAdapter());
    registerAdapter(LocalFavoriteAdapter());
  }
}
